name: "Build Firefox"

on:
    workflow_dispatch:
        inputs:
            sha:
                description: "Revision to build from"
                required: true
                type: string

env:
    SCCACHE_VERSION: "0.5.4"

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Set initial environment
              run: |
                echo "START_TIME_MS=$(($(date +%s%N)/1000000))" >> "$GITHUB_ENV"
                echo "FF_VERSION=$(curl https://raw.githubusercontent.com/dothq/gecko-dev/${{ inputs.sha }}/browser/config/version.txt)" >> "$GITHUB_ENV"

            - name: Clone scripts repository
              run: |
                git clone --depth 1 ${{ github.server_url }}/${{ github.repository }} ~/gd-scripts
                cd ~/gd-scripts && npm install 

            - name: Get current job ID
              uses: Tiryoh/gha-jobid-action@41f11aceecb8afcc9a3d9383242b9bad5a7a7cc3
              id: jobs
              with:
                github_token: ${{ secrets.ROBOT_TOKEN }}
                job_name: "${{ github.job }} (${{ matrix.os }})"

            - name: Update run state
              env:
                GH_APP_ID: ${{ secrets.GH_APP_ID }}
                GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
                RUN_NAME: "${{ github.job }} (${{ matrix.os }})"
                HEAD_SHA: ${{ inputs.sha }}
                DETAILS_URL: https://workflow-redir.dev.dothq.org/api/go?run_id=${{ github.run_id }}&job_id=${{ steps.jobs.outputs.job_id }}
                VERSION: ${{ env.FF_VERSION }}
              run: node ~/gd-scripts/src/set-run-state.js

            - name: Checkout source tree
              uses: actions/checkout@v3
              with:
                repository: dothq/gecko-dev
                ref: ${{ inputs.sha }}

            - name: Install dependencies
              run: |
                apt-get install -y curl \
                                   python3 \
                                   python3-pip
                curl -L https://github.com/mozilla/sccache/releases/download/v${{ env.SCCACHE_VERSION }}/sccache-v${{ env.SCCACHE_VERSION }}-$(uname -m)-unknown-linux-musl.tar.gz | tar -xzf -
                mv sccache-v${{ env.SCCACHE_VERSION }}-$(uname -m)-unknown-linux-musl/sccache /usr/local/bin/
                ./mach --no-interactive bootstrap --application-choice browser

            - name: Configure the build
              run: |
                rm mozconfig
                touch mozconfig
                echo "ac_add_options --with-ccache=sccache" >> mozconfig

            - name: Build the source tree
              id: build
              continue-on-error: true
              run: |
                echo "Compilation started at $(date '+%a %d %b %Y %H:%M:%S %Z')."
                ./mach build >/dev/null

            - name: Update run state
              timeout-minutes: 5
              if: always()
              env:
                GH_APP_ID: ${{ secrets.GH_APP_ID }}
                GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
                CONCLUSION: ${{ steps.build.outcome }}
                START_TIME_MS: ${{ env.START_TIME_MS }}
                RUN_NAME: "${{ github.job }} (${{ matrix.os }})"
                VERSION: ${{ env.FF_VERSION }}
              run: node ~/gd-scripts/src/set-run-state.js 