name: "Pull from upstream"

on:
    schedule:
        - cron: "0 12 * * SAT" # at 12pm noon every saturday
    workflow_dispatch:

jobs:
    pull:
        runs-on: ubuntu-latest
        steps:
            - name: Get current release version
              run: |
                curl https://raw.githubusercontent.com/mozilla/gecko-dev/release/browser/config/version.txt > current_version.txt
            
            - name: Compare versions
              run: |
                CURRENT_VERSION=$(cat current_version.txt)
                npm init -y
                npm i compare-versions
                node -e "\
                    var e = require('compare-versions').compareVersions('$CURRENT_VERSION', '${{ vars.PREV_CHECK_VERSION }}' == '' ? '$CURRENT_VERSION' : '${{ vars.PREV_CHECK_VERSION }}') == 1 ? 0 : 1;\
                    console.log(e ? 'No changes to pull!' : 'Pulling changes...');\
                    process.exit(e);\
                "

            - name: Store current version
              env:
                  GH_TOKEN: ${{ env.ROBOT_TOKEN }}
              run: |
                CURRENT_VERSION=$(cat current_version.txt)
                gh api --method POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    /repos/dothq/gecko-dev-scripts/actions/variables \
                    -f name='PREV_CHECK_VERSION' \
                    -f value="$CURRENT_VERSION"